inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 120

Naming/FileName:
  Exclude:
    - 'lib/rabbitmq-graph.rb'
