inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Layout/LineLength:
  Max: 120

Naming/FileName:
  Exclude:
    - 'lib/rabbitmq-graph.rb'

Style/HashTransformValues:
  Enabled: true

Style/HashTransformKeys:
  Enabled: false # Disabled while Ruby 2.4 is supported

Style/HashEachMethods:
  Enabled: true
