defaults: &defaults
  working_directory: ~/rabbitmq-graph
  docker:
    - image: ruby:3.0-alpine3.16

prepare_environment: &prepare_environment
  run:
    name: Prepare environment
    command: |
      apk add --no-cache --no-progress build-base curl git
      gem update --system 3.3.24

restore_gems: &restore_gems
  restore_cache:
    keys:
      - v1-gems-{{ checksum "Gemfile.lock" }}
      - v1-gems

install_gems: &install_gems
  run:
    name: Install dependencies
    command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle

cache_gems: &cache_gems
  save_cache:
    key: v1-gems-{{ checksum "Gemfile.lock" }}
    paths:
     - vendor/bundle

version: 2
jobs:
  rubocop:
    <<: *defaults
    steps:
      - *prepare_environment
      - checkout
      - *restore_gems
      - *install_gems
      - *cache_gems
      - run:
          name: Run rubocop
          command: bundle exec rubocop
  tests:
    <<: *defaults
    steps:
      - *prepare_environment
      - checkout
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - *restore_gems
      - *install_gems
      - *cache_gems
      - run:
          name: Run tests
          command: |
            ./cc-test-reporter before-build
            bundle exec rspec
            ./cc-test-reporter after-build --coverage-input-type simplecov --exit-code $?
      - store_artifacts:
          path: coverage

workflows:
  version: 2
  build:
    jobs:
      - rubocop
      - tests
