name: Integration Test
on: [push]

jobs:
  run:
    strategy:
      matrix:
        rabbitmq_version: ['3.8', '3.9']
        ruby_version: ['2.6', '2.7', '3.0']
    name: rabbitmq-${{ matrix.rabbitmq_version }} with ruby-${{ matrix.ruby_version }}
    runs-on: ubuntu-latest
    services:
      rabbitmq:
        image: rabbitmq:${{ matrix.rabbitmq_version }}-management-alpine
        ports:
          - 5672:5672
          - 15672:15672
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
      - uses: ifaxity/wait-on-action@v1
        with:
          resource: http://localhost:15672
      - run: bundle exec rspec --tag integration
        env:
          RABBITMQ_API_URI: http://guest:guest@localhost:15672
          RABBITMQ_URI: amqp://guest:guest@localhost:5672
